### ISSUE TITLE
AssertionError -- error help

### ISSUE THREAD

**Issue by magruca** [jnothman/UpSetPlot#87]
I'm attempting to integrate the upsetplot library into a data visualization script but am running into an AssertionError. My code looks like this:

```
df = pd.DataFrame({'motifs': unique_motifs, args.plot_labels[0]: a, args.plot_labels[1]: b, args.plot_labels[2]: c, args.plot_labels[3]: d})
plot_df = df.fillna(False).groupby(args.plot_labels).count()['motifs']
print(plot_df)
plot(plot_df)
plt.savefig('%s/%s_upset.png' % (args.output, args.rootname), dpi=600)
```
And the output/error from the above code I'm getting is as follows:

```
cat0   cat1   cat2   cat3 
False  False  False  True     55
              True   False     8
                     True      4
       True   False  False     5
                     True      3
              True   False     5
                     True      7
True   False  False  False     5
                     True      5
              True   False     6
                     True      2
       True   False  False     4
                     True      4
              True   False    37
                     True     53
Name: motifs, dtype: int64
Traceback (most recent call last):
  File "/home/mgruca/dowell/scripts/venn_diagram_tf_intersect.py", line 253, in <module>
    main()
  File "/home/mgruca/dowell/scripts/venn_diagram_tf_intersect.py", line 209, in main
    plot(plot_df)
  File "/home/mgruca/venv/lib64/python3.7/site-packages/upsetplot/plotting.py", line 630, in plot
    return UpSet(data, **kwargs).plot(fig)
  File "/home/mgruca/venv/lib64/python3.7/site-packages/upsetplot/plotting.py", line 301, in __init__
    sum_over=sum_over)
  File "/home/mgruca/venv/lib64/python3.7/site-packages/upsetplot/plotting.py", line 92, in _process_data
    assert all(set([True, False]) >= set(level) for level in agg.index.levels)
AssertionError
```

I'm hoping you can help clarify what this issue is/where I'm going wrong. Thanks a bunch for any help!

**Comment by magruca** [comment]
Also my first thought is it might be a bug in the lengths of my lists not matching up, but I ran the following:
```
assert len(a) == len(b) == len(c) == len(d) == len(unique_motifs)
print(len(a), len(b), len(c), len(d), len(unique_motifs))
```

but got the following back without error:
```
203 203 203 203 203
```

**Comment by jnothman** [comment]
Thanks for reporting the issue.

Is there a chance you can provide or invent data with which I can run your
code? That will make it much easier for me to identify what's going on.
Thanks

**Comment by magruca** [comment]
Sure is the dataframe good enough? I'll attach that here...
[upset_df.txt](https://github.com/jnothman/UpSetPlot/files/3893846/upset_df.txt)

**Comment by magruca** [comment]
Still trying to chase this down. Tried this just loading the dataframe from the text file:
```
df_import = pd.read_csv('/home/mgruca/dowell/sasse/unstimulated_proseq/figures/upset_df.txt', sep='\t', usecols=[1,2,3,4,5])
```

and the same lines of code following above and was able to produce the plot:
![unstimulated_pro_upset](https://user-images.githubusercontent.com/37707530/69671601-a41e4a80-1053-11ea-8d59-c3fdf67b4bff.png)

Both dataframes look the same, so I'm trying to figure out what I'm missing...
```
head(df)
     motifs   cat0   cat1   cat2   cat3
0      HELT   True   True   True  False
1    ZNF487   True   True   True   True
2      RELA  False  False  False   True
3     RUNX1  False  False  False   True
4     GLIS2  False  False  False   True
5    ZNF789  False   True   True  False
6     ZNF71  False  False  False   True
7      TBX2  False  False  False   True
8    STAT5A  False   True   True   True
9         T   True   True   True   True
10   ZNF324   True   True   True   True
[203 rows x 5 columns]

head(df_import)
     motifs   cat0   cat1   cat2   cat3
0      HELT   True   True   True  False
1    ZNF487   True   True   True   True
2      RELA  False  False  False   True
3     RUNX1  False  False  False   True
4     GLIS2  False  False  False   True
5    ZNF789  False   True   True  False
6     ZNF71  False  False  False   True
7      TBX2  False  False  False   True
8    STAT5A  False   True   True   True
9         T   True   True   True   True
10   ZNF324   True   True   True   True
[203 rows x 5 columns]
```

**Comment by jnothman** [comment]
In #76 I made a change that may fix your problem. Can you please try
installing the development version - i.e. pip install
https://github.com/jnothman/UpSetPlot/archive/master.zip - and rerunning
your code? thanks

**Comment by magruca** [comment]
The error definitely helps with clarity, thank you! It's a dtype error which I figured yesterday but never got a chance to go back to it. That said, with new dev version this is the error you get instead:
```
  File "/home/mgruca/dowell/scripts/tf_intersect.py", line 262, in <module>
    main()
  File "/home/mgruca/dowell/scripts/tf_intersect.py", line 229, in main
    upset = UpSet(full_plot_df, subset_size='count', intersection_plot_elements=3, sort_by='cardinality', show_counts=True)
  File "/home/mgruca/venv/lib64/python3.7/site-packages/upsetplot/plotting.py", line 311, in __init__
    sum_over=sum_over)
  File "/home/mgruca/venv/lib64/python3.7/site-packages/upsetplot/plotting.py", line 109, in _process_data
    df = _check_index(df)
  File "/home/mgruca/venv/lib64/python3.7/site-packages/upsetplot/plotting.py", line 91, in _check_index
    raise ValueError('The DataFrame has values in its index that are not '
ValueError: The DataFrame has values in its index that are not boolean
```
Checking both the in-line dataframe and the loaded dataframe:
```
motif_key    object
cat0         object
cat1         object
cat2         object
cat3         object
cat4         object
cat5         object
cat6         object
cat7         object
cat8         object
dtype: object
motif_key    object
cat0           bool
cat1           bool
cat2           bool
cat3           bool
cat4           bool
cat5           bool
cat6           bool
cat7           bool
cat8           bool
```

obviously points out the issue. This was resolved when I switched them back over to bool. Appreciate your help in addressing this!
